Hyeongwon-up/Bithumb-Virspit-Server

- virspit-gateway/build.gradle
> <build> gateway dependency 추가

- virspit-gateway/build.gradle
> Gateway/first PR test

- virspit-gateway/build.gradle
- virspit-gateway/src/main/java/com/virspit/gateway/VirspitGatewayApplication.java
- virspit-gateway/src/main/java/com/virspit/gateway/filter/JwtRequestFilter.java
- virspit-gateway/src/main/java/com/virspit/gateway/filter/Role.java
User 서버 호출을 위해서는 통과해야할 필터를 추가했습니다.
메인 어플리케이션은 다른 서버 필터 적용 후 정리하겠습니다~!!
> <Feat> User 서버 jwt 필터 추가

- virspit-auth/src/main/java/com/virspit/virspitauth/VirspitAuthApplication.java
- virspit-auth/src/main/java/com/virspit/virspitauth/domain/member/controller/MemberController.java
- virspit-auth/src/main/java/com/virspit/virspitauth/domain/member/dto/response/MemberSignInResponseDto.java
- virspit-auth/src/main/java/com/virspit/virspitauth/domain/member/service/MemberService.java
> <hotfix> commit fix

- virspit-order/build.gradle
- virspit-order/src/main/java/com/virspit/virspitorder/config/SwaggerConfig.java
- virspit-order/src/main/java/com/virspit/virspitorder/controller/OrderController.java
- virspit-order/src/main/java/com/virspit/virspitorder/dto/request/OrdersRequestDto.java
- virspit-order/src/main/java/com/virspit/virspitorder/dto/response/OrdersResponseDto.java
- virspit-order/src/main/java/com/virspit/virspitorder/entity/Orders.java
- virspit-order/src/main/java/com/virspit/virspitorder/repository/OrderRepository.java
- virspit-order/src/main/java/com/virspit/virspitorder/service/OrderService.java
- virspit-order/src/test/java/com/virspit/virspitorder/controller/OrderControllerTest.java
orders 참고하시라고 일단 올려둡니다! 
entity, dto 정보들에 대해 생각을 해봐야 할 것 같아요..ㅎ.ㅎ
product 정보를 같이 받아서 쓰는게 어떨까합니다(이름이라도)
> <test> order getAll

- virspit-product/build.gradle
- virspit-product/src/main/java/com/virspit/virspitproduct/VirspitProductApplication.java
- virspit-product/src/main/java/com/virspit/virspitproduct/domain/sports/controller/SportsController.java
- virspit-product/src/main/java/com/virspit/virspitproduct/domain/sports/dto/request/SportsStoreRequestDto.java
- virspit-product/src/main/java/com/virspit/virspitproduct/domain/sports/entity/Sports.java
- virspit-product/src/main/java/com/virspit/virspitproduct/domain/teamplayer/controller/TeamPlayerController.java
- virspit-product/src/main/java/com/virspit/virspitproduct/domain/teamplayer/dto/request/TeamPlayerStoreRequestDto.java
- virspit-product/src/main/java/com/virspit/virspitproduct/domain/teamplayer/dto/response/TeamPlayerResponseDto.java
- virspit-product/src/main/java/com/virspit/virspitproduct/domain/teamplayer/entity/TeamPlayer.java
- virspit-product/src/main/java/com/virspit/virspitproduct/domain/teamplayer/repository/TeamPlayerRepository.java
- virspit-product/src/main/java/com/virspit/virspitproduct/domain/teamplayer/service/TeamPlayerService.java
- virspit-product/src/main/java/com/virspit/virspitproduct/util/file/FileStore.java
- virspit-product/src/main/resources/application.yml
- virspit-product/src/test/java/com/virspit/virspitproduct/domain/teamplayer/controller/TeamPlayerControllerTest.java
- virspit-product/src/test/java/com/virspit/virspitproduct/domain/teamplayer/repository/TeamPlayerRepositoryTest.java
- virspit-product/src/test/java/com/virspit/virspitproduct/domain/teamplayer/service/TeamPlayerServiceTest.java
TeamPlayer 추가, 검색, 아이디로 조회, 전체 조회, 수정, 제거 기능 및 테스트 구현
> <Feat> TeamPlayer 도메인 관련 기능, 테스트 구현

- virspit-auth/src/main/java/com/virspit/virspitauth/controller/AuthController.java
- virspit-auth/src/main/java/com/virspit/virspitauth/dto/request/MemberChangePwdRequestDto.java
- virspit-auth/src/main/java/com/virspit/virspitauth/feign/MemberServiceFeignClient.java
- virspit-auth/src/main/java/com/virspit/virspitauth/service/MemberService.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/controller/MemberController.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/dto/request/MemberChangePwdRequestDto.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/feign/AuthServiceFeignClient.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/service/MemberService.java
> 비밀번호 변경 기능 추가 ( AuthServiceFeignclient 생성)

- virspit-order/src/main/java/com/virspit/virspitorder/service/NftService.java
- virspit-order/src/main/resources/application.yml
- virspit-order/src/test/java/com/virspit/virspitorder/service/KasApiTest.java
payToAdminFeesByCustomer : 멤버가 수수료를 부담하고 클레이를 전송하는 메서드 
issueToken : 구매할때 nft에 대한 토큰 발행 (소유주:구매자)
tokenId를 지정해줘야 하는데 16진수로 변환한 값이므로, 멤버가 가진 nft 갯수 +1 로 수를 지정해주는건 어떨까요??
> <Feat> Order nft 

- virspit-user/build.gradle
- virspit-user/src/main/java/com/virspit/virspituser/config/KasConfig.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/controller/MemberController.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/entity/Member.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/service/MemberService.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/wallet/controller/WalletController.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/wallet/entity/Wallet.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/wallet/repository/WalletRepository.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/wallet/service/WalletService.java
- virspit-user/src/main/resources/application.yml
- virspit-user/src/test/java/com/virspit/virspituser/domain/wallet/service/WalletServiceTest.java
Member 와 wallet 을 단방향 onoToone으로 매핑해주었습니당
> 회원가입시 지갑생성.

- virspit-auth/src/main/java/com/virspit/virspitauth/dto/model/Member.java
- virspit-auth/src/main/java/com/virspit/virspitauth/dto/model/Wallet.java
- virspit-auth/src/test/java/com/virspit/virspitauth/feign/MemberServiceFeignClientTest.java
- virspit-order/build.gradle
- virspit-order/src/main/java/com/virspit/virspitorder/VirspitOrderApplication.java
- virspit-order/src/main/java/com/virspit/virspitorder/config/KafkaProducerConfig.java
- virspit-order/src/main/java/com/virspit/virspitorder/controller/OrderController.java
- virspit-order/src/main/java/com/virspit/virspitorder/entity/Orders.java
- virspit-order/src/main/java/com/virspit/virspitorder/feign/MemberServiceFeignClient.java
- virspit-order/src/main/java/com/virspit/virspitorder/service/OrderService.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/entity/Member.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/wallet/controller/WalletController.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/wallet/entity/Wallet.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/wallet/service/WalletService.java
> 상품 주문하기 추가

- virspit-product/src/main/java/com/virspit/virspitproduct/domain/common/BaseEntity.java
- virspit-product/src/main/java/com/virspit/virspitproduct/domain/product/entity/NftInfo.java
- virspit-product/src/main/java/com/virspit/virspitproduct/domain/product/entity/Product.java
- virspit-product/src/main/java/com/virspit/virspitproduct/domain/product/repository/ProductRepository.java
- virspit-product/src/main/resources/application.yml
- virspit-product/src/test/java/com/virspit/virspitproduct/domain/product/repository/ProductRepositoryTest.java
Product 관련 Entity 수정
ProductRepository에 query method 추가
ProductRepository 테스트 추가
> Product Repository 관련 구현

- virspit-auth/src/main/java/com/virspit/virspitauth/controller/AuthController.java
- virspit-auth/src/main/java/com/virspit/virspitauth/service/MemberService.java
> 로그아웃 기능 추가 (access,refresh 토큰 모두 파기 및 블랙리스트 등록)

- virspit-user/src/main/java/com/virspit/virspituser/domain/favorite/controller/FavoriteController.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/favorite/dto/response/FavoriteResponseDto.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/favorite/entity/Favorite.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/favorite/repository/FavoriteRepository.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/favorite/service/FavoriteService.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/entity/Member.java
- virspit-user/src/test/java/com/virspit/virspituser/domain/favorite/service/FavoriteServiceTest.java
> <Feat> 상품 좋아요 , 좋아요 취소, 좋아요한 상품 목록 불러오기 추가

- virspit-order/src/main/java/com/virspit/virspitorder/config/KafkaProducerConfig.java
- virspit-order/src/main/java/com/virspit/virspitorder/controller/OrderController.java
- virspit-order/src/main/java/com/virspit/virspitorder/dto/request/OrderMemoRequestDto.java
- virspit-order/src/main/java/com/virspit/virspitorder/dto/request/OrdersRequestDto.java
- virspit-order/src/main/java/com/virspit/virspitorder/entity/Orders.java
- virspit-order/src/main/java/com/virspit/virspitorder/service/OrderService.java
- virspit-order/src/test/java/com/virspit/virspitorder/controller/OrderControllerTest.java
> <Feat> order memo 수정 api

- virspit-user/src/main/java/com/virspit/virspituser/domain/member/dto/request/MemberSignUpRequestDto.java
- virspit-user/src/test/java/com/virspit/virspituser/domain/member/service/MemberServiceTest.java
> <test> memberService 테스트 코드  작성

- virspit-user/Dockerfile
- virspit-user/build.gradle
- virspit-user/src/main/resources/application-stage.yml
> virspit-user 배포

- virspit-eureka-server/Dockerfile
> eureka dockerfile 추가

- virspit-gateway/Dockerfile
- virspit-gateway/src/main/resources/application-stage.yml
> gateway 배포 

- virspit-auth/Dockerfile
- virspit-auth/build.gradle
- virspit-auth/src/main/resources/application-stage.yml
> auth 서버 배포

- virspit-product/build.gradle
- virspit-product/src/main/java/com/virspit/virspitproduct/VirspitProductApplication.java
- virspit-product/src/main/java/com/virspit/virspitproduct/domain/teamplayer/controller/TeamPlayerController.java
- virspit-product/src/main/java/com/virspit/virspitproduct/domain/teamplayer/dto/request/TeamPlayerStoreRequestDto.java
- virspit-product/src/main/java/com/virspit/virspitproduct/domain/teamplayer/dto/response/TeamPlayerResponseDto.java
- virspit-product/src/main/java/com/virspit/virspitproduct/domain/teamplayer/repository/TeamPlayerRepository.java
- virspit-product/src/main/java/com/virspit/virspitproduct/domain/teamplayer/service/TeamPlayerService.java
- virspit-product/src/main/resources/application-stage.yml
> 팀/플레이어 스웨거 적용

- virspit-order/src/main/resources/application-stage.yml
> order 서버 배포 setting

- virspit-order/src/main/java/com/virspit/virspitorder/config/WebConfig.java
> order 서버 cors 해결용 webconfig

- virspit-auth/src/main/java/com/virspit/virspitauth/controller/AuthController.java
- virspit-auth/src/main/java/com/virspit/virspitauth/dto/response/MemberSignInResponseDto.java
- virspit-auth/src/main/java/com/virspit/virspitauth/service/MemberService.java
> <Refac> auth login

- virspit-auth/src/main/java/com/virspit/virspitauth/error/GlobalControllerExceptionHandler.java
> <feat> feignException

- virspit-auth/src/main/java/com/virspit/virspitauth/controller/AuthController.java
> <refac> edit verify email

- virspit-auth/src/main/java/com/virspit/virspitauth/controller/AuthController.java
- virspit-auth/src/main/java/com/virspit/virspitauth/dto/request/InitPwdRequestDto.java
- virspit-auth/src/main/java/com/virspit/virspitauth/feign/MemberServiceFeignClient.java
- virspit-auth/src/main/java/com/virspit/virspitauth/service/MemberService.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/controller/MemberController.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/controller/MemberFeignController.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/dto/request/InitPwdRequestDto.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/entity/Member.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/service/MemberService.java
> <refac> initPassword

- virspit-auth/src/main/java/com/virspit/virspitauth/controller/AuthController.java
- virspit-auth/src/main/java/com/virspit/virspitauth/dto/request/MemberChangePwdRequestDto.java
- virspit-auth/src/main/java/com/virspit/virspitauth/service/MemberService.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/controller/MemberFeignController.java
> <refac> change pwd

- WebConnectTest/index.html
- WebConnectTest/index.js
> <feat> front test

- virspit-auth/src/main/java/com/virspit/virspitauth/VirspitAuthApplication.java
- virspit-gateway/src/main/java/com/virspit/gateway/VirspitGatewayApplication.java
- virspit-user/src/main/java/com/virspit/virspituser/VirspitUserApplication.java
> <refac> enable eureka client, feign clients

- virspit-auth/src/main/java/com/virspit/virspitauth/feign/MemberServiceFeignClient.java
- virspit-auth/src/main/resources/application-stage.yml
- virspit-gateway/src/main/resources/application-stage.yml
- virspit-user/src/main/resources/application-stage.yml
> <refac> 서비스간 통신 시 hostname 보다 ip 를 우선 사용으로 변경

- virspit-auth/src/main/java/com/virspit/virspitauth/config/RedisConfig.java
- virspit-auth/src/main/resources/application-stage.yml
> <feat> Redis config, yml  setting for ec2

- virspit-auth/src/main/java/com/virspit/virspitauth/controller/AdviceController.java
- virspit-auth/src/main/java/com/virspit/virspitauth/controller/AuthController.java
- virspit-auth/src/main/java/com/virspit/virspitauth/dto/request/MemberSignInRequestDto.java
- virspit-auth/src/main/java/com/virspit/virspitauth/dto/request/MemberSignUpRequestDto.java
- virspit-auth/src/main/java/com/virspit/virspitauth/dto/response/MemberSignUpResponseDto.java
- virspit-auth/src/main/java/com/virspit/virspitauth/feign/MemberServiceFeignClient.java
- virspit-auth/src/main/java/com/virspit/virspitauth/service/MemberService.java
- virspit-auth/src/test/java/com/virspit/virspitauth/service/MemberServiceTest.java
- virspit-gateway/build.gradle
- virspit-gateway/src/main/java/com/virspit/gateway/error/ErrorCode.java
- virspit-gateway/src/main/java/com/virspit/gateway/error/ErrorResponse.java
- virspit-gateway/src/main/java/com/virspit/gateway/error/GlobalControllerExceptionHandler.java
- virspit-gateway/src/main/java/com/virspit/gateway/error/exception/BusinessException.java
- virspit-gateway/src/main/java/com/virspit/gateway/error/exception/EntityNotFoundException.java
- virspit-gateway/src/main/java/com/virspit/gateway/error/exception/InvalidValueException.java
- virspit-gateway/src/main/java/com/virspit/gateway/filter/JwtUserRequestFilter.java
- virspit-gateway/src/main/resources/application-stage.yml
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/controller/MemberFeignController.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/dto/response/MemberSignUpResponseDto.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/entity/Member.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/service/MemberService.java
> <Refac> auth for admin

- virspit-order/src/main/java/com/virspit/virspitorder/controller/OrderController.java
- virspit-order/src/main/java/com/virspit/virspitorder/dto/response/NftInfo.java
- virspit-order/src/main/java/com/virspit/virspitorder/dto/response/ProductResponseDto.java
- virspit-order/src/main/java/com/virspit/virspitorder/entity/Orders.java
- virspit-order/src/main/java/com/virspit/virspitorder/feign/MemberServiceFeignClient.java
- virspit-order/src/main/java/com/virspit/virspitorder/feign/ProductServiceFeignClient.java
- virspit-order/src/main/java/com/virspit/virspitorder/service/NftService.java
- virspit-order/src/main/java/com/virspit/virspitorder/service/OrderService.java
- virspit-order/src/main/resources/application.yml
- virspit-order/src/main/resources/test.yml
- virspit-order/src/test/java/com/virspit/virspitorder/feign/MemberServiceFeignClientTest.java
- virspit-order/src/test/java/com/virspit/virspitorder/feign/ProductServiceFeignClientTest.java
- virspit-order/src/test/java/com/virspit/virspitorder/service/KasApiTest.java
* order 주문시 service 로직에 nft 서비스 추가
> <Fix> Order 서비스 수정 

- virspit-product/src/main/java/com/virspit/virspitproduct/VirspitProductApplication.java
- virspit-product/src/main/resources/application-stage.yml
> <feat> eureka client product

- virspit-order/src/main/java/com/virspit/virspitorder/VirspitOrderApplication.java
- virspit-order/src/main/resources/application-stage.yml
> <feat> eureka client order

- virspit-gateway/src/main/java/com/virspit/gateway/filter/JwtAdminRequestFilter.java
- virspit-gateway/src/main/resources/application-stage.yml
> <refac> gateway

- virspit-auth/src/main/java/com/virspit/virspitauth/dto/request/MemberSignUpRequestDto.java
- virspit-auth/src/main/java/com/virspit/virspitauth/dto/response/MemberSignUpResponseDto.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/controller/MemberController.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/dto/request/MemberEditInfoRequestDto.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/dto/request/MemberSignInRequestDto.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/dto/request/MemberSignUpRequestDto.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/dto/response/MemberSignUpResponseDto.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/entity/Member.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/service/MemberService.java
> <feat> Member Entitiy Phone 추가

- virspit-auth/src/main/java/com/virspit/virspitauth/controller/AuthController.java
- virspit-auth/src/main/java/com/virspit/virspitauth/dto/model/Member.java
- virspit-auth/src/main/java/com/virspit/virspitauth/feign/MemberServiceFeignClient.java
- virspit-auth/src/main/java/com/virspit/virspitauth/service/MemberService.java
- virspit-gateway/src/main/resources/application-stage.yml
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/controller/MemberFeignController.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/service/MemberService.java
> <refac> Deprecated controller,service 제거

- virspit-auth/src/main/java/com/virspit/virspitauth/controller/AuthController.java
- virspit-auth/src/main/java/com/virspit/virspitauth/dto/model/Member.java
- virspit-auth/src/main/java/com/virspit/virspitauth/dto/response/MemberInfoResponseDto.java
- virspit-auth/src/main/java/com/virspit/virspitauth/dto/response/MemberSignInResponseDto.java
- virspit-auth/src/main/java/com/virspit/virspitauth/feign/MemberServiceFeignClient.java
- virspit-auth/src/main/java/com/virspit/virspitauth/service/MemberService.java
- virspit-gateway/src/main/resources/application-stage.yml
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/controller/MemberController.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/controller/MemberFeignController.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/dto/response/MemberInfoResponseDto.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/service/MemberService.java
> <refac> login response dto

- virspit-service/docker-compose.yml
- virspit-service/src/main/java/com/virspit/virspitservice/config/WebConfig.java
- virspit-service/src/main/java/com/virspit/virspitservice/domain/product/repository/ProductDocRepository.java
- virspit-service/src/main/java/com/virspit/virspitservice/domain/product/service/ProductService.java
> <Fix> Listing/fix

- virspit-auth/src/main/java/com/virspit/virspitauth/dto/response/MemberInfoResponseDto.java
> <feat> Login 성공할 때, 유저 아이디도 반환.

- virspit-auth/build.gradle
- virspit-auth/src/main/resources/application.yml
- virspit-auth/src/main/resources/logback.xml
- virspit-gateway/build.gradle
- virspit-gateway/src/main/resources/application-stage.yml
- virspit-gateway/src/main/resources/application.yml
- virspit-gateway/src/main/resources/logback.xml
- virspit-product/build.gradle
- virspit-product/src/main/resources/application.yml
- virspit-product/src/main/resources/logback.xml
- virspit-user/build.gradle
- virspit-user/src/main/resources/application.yml
- virspit-user/src/main/resources/logback.xml
> <feat> ELK Logging setting

- virspit-order/src/main/java/com/virspit/virspitorder/controller/OrderController.java
- virspit-order/src/main/java/com/virspit/virspitorder/dto/response/ProductResponseDto.java
- virspit-order/src/main/java/com/virspit/virspitorder/feign/ProductServiceFeignClient.java
- virspit-order/src/main/java/com/virspit/virspitorder/service/OrderService.java
- virspit-order/src/main/java/com/virspit/virspitorder/util/StringUtils.java
- virspit-service/build.gradle
- virspit-service/src/main/java/com/virspit/virspitservice/domain/product/controller/ProductController.java
* order -> controller 날짜 포맷 수정 
* listing -> logging dependency 추가 , kafka data 싱크 용 controller 추가
> <Fix> order, listing 서버 수정

- virspit-auth/src/test/java/com/virspit/virspitauth/service/MemberServiceTest.java
- virspit-gateway/src/main/resources/application-stage.yml
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/controller/MemberFeignController.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/repository/MemberRepository.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/member/service/MemberService.java
- virspit-user/src/test/java/com/virspit/virspituser/domain/member/service/MemberServiceTest.java
> <test> user service unit test

- virspit-auth/src/main/java/com/virspit/virspitauth/service/MemberService.java
> <refac> 중복체크 -> 이메일 인증시 체크로

- virspit-user/src/main/java/com/virspit/virspituser/domain/favorite/repository/FavoriteRepository.java
- virspit-user/src/main/java/com/virspit/virspituser/domain/favorite/service/FavoriteService.java
- virspit-user/src/main/java/com/virspit/virspituser/global/error/ErrorCode.java
- virspit-user/src/main/java/com/virspit/virspituser/global/error/exception/InvalidValueException.java
> <feat> favorite exception
